CREATE TABLE IF NOT EXISTS `cinematics` (
	`id` INT AUTO_INCREMENT,
    `title` VARCHAR(255) NOT NULL,
    `synopsis` TEXT NOT NULL,
    `tagline` VARCHAR(255) NOT NULL,
    `released_year` YEAR(4) NOT NULL,
    `poster_path` TEXT NOT NULL,
    `backdrop_path` TEXT,
    `imdb_code` VARCHAR(255) NOT NULL,
    `imdb_rating` DECIMAl(2,1),
    `rt_score` DECIMAl(3,1),
    `trailer_link` TEXT NOT NULL,
    `subtitle_link` TEXT,
    `duration` INT NOT NULL,
    `film_industry` ENUM('hollywood', 'bollywood', 'lollywood', 'tamil-nadu', 'korean') NOT NULL DEFAULT 'hollywood',
    `type` ENUM('movie', 'season') NOT NULL DEFAULT 'movie',
    `status` ENUM('upcoming', 'released', 'deleted', 'disabled') NOT NULL DEFAULT 'upcoming',
    `pg_rating` ENUM('PG-8', 'PG-12', 'PG-14', 'PG-16', 'PG-18') NOT NULL,
    `original_language` ENUM('english', 'hindi', 'urdu', 'tamil', 'korean') NOT NULL DEFAULT 'english',
    `budget` DECIMAL(15, 2) NOT NULL,
    `revenue` DECIMAL(15, 2) NOT NULL,
    `director_id` INT NOT NULL,
    `created_at` DATETIME DEFAULT CURRENT_TIMESTAMP,
     FOREIGN KEY (`director_id`) REFERENCES artists(`id`),
     PRIMARY KEY (`id`),
     UNIQUE KEY `title_year_index` (`title`, `released_year`)
);